apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service-tech-docs
  description: pipeline build and deploy
  annotations:
       harness.io/pipeline-url: |
         labelA: https://app.harness.io/ng/account/6h56F6WNQna2bDWBKfPMLw/module/cd/orgs/default/projects/communityeng/pipelines/nativeawslambda/pipeline-studio?storeType=INLINE
       jira/project-key: IDP
       github.com/project-slug: Debanitrkl/backstage-test
       backstage.io/techdocs-ref: url:https://github.com/Debanitrkl/backstage-test/tree/main
       pagerduty.com/service-id: P09N5FE
       pagerduty.com/integration-key: R03DT3PRH1SU1J014M3FQDUQB53B4CUH
  tags:
    - java
  
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: debabrata.panigrahi
