pipeline:
  name: demo-gitsync
  identifier: demogitsync
  projectIdentifier: idpprojectsc
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: create-repo
        identifier: createrepo
        description: ""
        type: IDP
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: CreateRepo
                  name: CreateRepo_1
                  identifier: CreateRepo_1
                  spec:
                    connectorType: Github
                    connectorRef: account.debagithub
                    organization: <+pipeline.variables.organisation>
                    repository: <+pipeline.variables.repository>
                    repoType: public
        tags: {}
  variables:
    - name: organisation
      type: String
      description: ""
      required: false
      value: <+input>
    - name: repository
      type: String
      description: ""
      required: false
      value: <+input>
