pipeline:
  name: demo-gitsync
  identifier: demogitsync
  projectIdentifier: idpprojectsc
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: create-repo
        identifier: createrepo
        description: ""
        type: IDP
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: CreateRepo
                  name: CreateRepo_1
                  identifier: CreateRepo_1
                  spec:
                    connectorType: Github
                    connectorRef: deveshconn
                    organization: test-org-devesh
                    repository: test-demo-denanasdad
                    repoType: public
                    defaultBranch: main
        tags: {}
