apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service-deba-without-module
  description: pipeline build and deploy
  annotations:
       harness.io/services: |
         labelA: https://accounts.eu.harness.io/ng/account/MzUzMzUyMWUtYWU4Yy00Mz/module/cd/orgs/prateekorg/projects/prateekproject/services/sample
  tags:
    - java
  
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
spec:
  type: service
  lifecycle: experimental
  owner: idpplayacc
