apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iacm-test
  description: pipeline build and deploy
  annotations:
       harness.io/workspace-url: |
          workspaceA: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/module/iacm/orgs/default/projects/idpprojectsc/workspaces/demo/resources
  tags:
    - java
  
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
spec:
  type: service
  lifecycle: experimental
  owner: ccm
