apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: demo
  annotations:
    # optional annotations
    harness.io/pipelines: |
      Pipeline1: https://app.harness.io/ng/account/6h56F6WNQna2bDWBKfPMLw/cd/orgs/default/projects/Harnesspractise/pipelines/asdf/pipeline-studio/?storeType=INLINE
      Pipeline2: https://app.harness.io/ng/account/6h56F6WNQna2bDWBKfPMLw/cd/orgs/default/projects/Harnesspractise/pipelines/terraform_usecase/pipeline-studio/?storeType=INLINE
    harness.io/services: |
      Service1: <harness_service_url>
      Service2: <harness_service_url>
  tags:
    - java

  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a
