apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springbootservice
  title: Create a Springboot service
  description: A template for the scaffolder that creates a springboot service
  tags:
    - springboot
    - harness
spec:
  owner: debabrata.panigrahi@harness.io
  type: service
  parameters:
    - title: Springboot Service Details
      required:
        - project_name
        - github_repo
        - language
        - springBootVersion
        - project_type
        - group
        - artifact
        - packageName
        - packaging
        - javaVersion
      properties:
        project_name:
          title: Name of your new app
          type: string
          description: Unique name of the app
        github_repo:
          title: Name of the GitHub repository
          type: string
          description: This will be the name of Repository on Github
        project_type:
          type: string
          title: Project
          enum:
            - Gradle-Groovy
            - Gradle-Kotlin
            - Maven
          default: Maven
        language:
          type: string
          title: Programming Language
          enum:
            - Java
            - Kotlin
            - Groovy
          default: Java
        springBootVersion:
          type: string
          title: Spring Boot Version
          enum:
            - 2.7.17
            - 2.7.18 (SNAPSHOT)
            - 3.0.12
            - 3.0.13 (SNAPSHOT)
            - 3.1.5
            - 3.1.6 (SNAPSHOT)
            - 3.2.0 (RC2)
            - 3.2.0 (SNAPSHOT)
          default: 3.1.5
        group:
          type: string
          title: com.demo
          default: com.example
        artifact:
          type: string
          title: Artifact ID
          default: Default
        name:
          type: string
          title: Project Name
          default: Default Name for Spring Boot Project
        packageName:
          type: string
          title: com.example.demo
          default: com.example.default
        packaging:
          type: string
          title: Packaging
          enum:
            - Jar
            - War
          default: Jar
        javaVersion:
          type: string
          title: Java Version
          enum:
            - "8"
            - "11"
            - "17"
            - "21"
          default: 21
        owner:
          title: Choose an owner for the Service
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Creating Your springboot service
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/cd/orgs/default/projects/communityeng/pipelines/NewSpringBootProject/pipeline-studio?storeType=INLINE
        inputset:
          project_name: ${{ parameters.project_name }}
          github_repo: ${{ parameters.github_repo }}
          project_type: ${{ parameters.project_type }}
          language: ${{ parameters.language }}
          springBootVersion: ${{ parameters.springBootVersion }}
          group: ${{ parameters.group }}
          artifact: ${{ parameters.artifact }}
          packageName: ${{ parameters.packageName }}
          packaging: ${{ parameters.packaging }}
          javaVersion: ${{ parameters.javaVersion }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}


  
