apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-CA-2
  title: Test New Custom Actions
  description: A template to create a new service
  tags:
    - nextjs
    - react
    - javascript
spec:
  owner: debabrata.panigrahi@harness.io
  type: service
  parameters:
    - title: Trigger Details
      required:
        - triggerWebhookurl
      properties:
        triggerWebhookurl:
          title: trigger webhook URL
          type: string
        x_api_key:
          title: Harness Token
          type: string 
          ui:widget: password
  steps:
    - id: trigger
      name: Creating your react app
      action: trigger:trigger-pipeline-with-webhook
      input:
        triggerWebhookurl: ${{ parameters.triggerWebhookurl }}
        x_api_key: ${{ parameters.x_api_key }}
    # The final step is to register our new component in the catalog.
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
