apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-CA-1
  title: Test New Custom Actions
  description: A template to create a new service
  tags:
    - nextjs
    - react
    - javascript
spec:
  owner: debabrata.panigrahi@harness.io
  type: service
  parameters:
    - title: Service Details
      required:
        - x_api_key
      properties:
        x_api_key:
          title: Harness Token
          type: string          
  steps:
    - id: trigger
      name: Creating your react app
      action: trigger:create-and-trigger-pipeline-with-inputset
      input:
        triggerWebhookurl: "https://app.harness.io/gateway/pipeline/api/webhook/custom/v2?accountIdentifier=6h56F6WNQna2bDWBKfPMLw&orgIdentifier=default&projectIdentifier=Harnesspractise&pipelineIdentifier=asdf&triggerIdentifier=asdf"
        x_api_key: ${{ parameters.x_api_key }}
    # The final step is to register our new component in the catalog.
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
