apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-display-values
  title: Example Display Values Template
  description: A template to display previously entered values on another page
spec:
  owner: owner@company.com
  type: service
  parameters:
    - title: Service Details
      type: object
      required:
        - service_name
        - environment_type
      properties:
        service_name:
          title: Service Name
          type: string
          description: Enter the name of the service you are creating
        environment_type:
          title: Environment Type
          type: string
          description: Choose the environment
          enum:
            - dev
            - staging
            - prod

    - title: Review and Confirm
      type: object
      properties:
        review_service_name:
          type: string
          title: Service Name (Review)
          description: Review the service name you entered
          ui:field: TextArea
          ui:options:
            rows: 1
            readonly: true  # Make the field read-only
          placeholder: ${{ parameters.service_name }}  # Display the service name
        review_environment_type:
          type: string
          title: Environment Type (Review)
          description: Review the environment type you selected
          ui:field: TextArea
          ui:options:
            rows: 1
            readonly: true  # Make the field read-only
          placeholder: ${{ parameters.environment_type }}  # Display the environment type
  steps:
    - id: trigger
      name: Provision Service
      action: trigger:harness-custom-pipeline
      input:
        url: "YOUR_PIPELINE_URL"
        inputset:
          service_name: ${{ parameters.service_name }}
          environment_type: ${{ parameters.environment_type }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
