apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  description: pipeline build and deploy
  annotations:
       harness.io/pipelines: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/cd/orgs/default/projects/communityeng/pipelines/NewSpringBootProject/pipeline-studio?storeType=INLINE
       github.com/project-slug: harness/harness-core-ui
       grafana/dashboard-selector: "folderUrl == 'https://grafana.harness.io/dashboards/f/X3UO7QLVk/sto' || folderUrl == 'https://grafana.harness.io/dashboards/f/3oaJ5P94z/cie'"
       grafana/alert-label-selector: "destination=sto-prod-slack"
       grafana/overview-dashboard: "https://grafana.harness.io/d/-zsEc0J4k/sto-core-and-ticket-service?orgId=1"
       jira/project-key: IDP
       pagerduty.com/service-id: PFVOX97
  tags:
    - java
  
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
spec:
  type: service
  lifecycle: experimental
  owner: idpplayacc
