apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  description: this is a demo service
  annotations:
      harness.io/project-url: "https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/cd/orgs/default/projects/PREQA_NG_Pipelines/pipelines"
      github.com/project-slug: github/example-org/artist-website
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: qa
  owner: idp-eng
